project:
  type: website

website:
  title: "ML Blogs"
  navbar:
    left: 
      - text: Home
        href: https://vraj2811.netlify.app/
    right:
      - icon: github
        href: https://github.com/Vraj2811/

format:
  html: 
    theme: cyborg
    toc: true